// Rich dummy data for the Load Sample feature

export const SAMPLE_HOTEL_DATA = [
  {
    hotel_name: "The Grand Sakura Hotel",
    slug: "grand-sakura-hotel",
    address: "2-14-3 Shibuya, Shibuya-ku",
    country: "Japan",
    city: "Tokyo",
    category: "Luxury",
    stars: "5",
    rating: "4.8",
    number_of_reviews: "1243",
    price_per_night: "389",
    photo_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    languages_spoken: "Japanese, English, Mandarin",
    hotel_services: "Concierge, Valet Parking, Spa, Room Service",
    amenities: "Rooftop Pool, Fitness Center, Business Lounge, Japanese Garden",
    description: "Nestled in the heart of Shibuya, The Grand Sakura Hotel blends traditional Japanese aesthetics with modern luxury. Each of the 280 rooms features floor-to-ceiling windows with panoramic city views, handcrafted furniture, and a private onsen-style soaking tub.",
    url: "https://example.com/grand-sakura",
  },
  {
    hotel_name: "Azure Coast Resort & Spa",
    slug: "azure-coast-resort",
    address: "Boulevard de la Croisette 47",
    country: "France",
    city: "Cannes",
    category: "Resort",
    stars: "5",
    rating: "4.6",
    number_of_reviews: "876",
    price_per_night: "520",
    photo_url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    languages_spoken: "French, English, Italian, Spanish",
    hotel_services: "Private Beach, Butler Service, Helicopter Transfer, Michelin Restaurant",
    amenities: "Infinity Pool, Thalassotherapy Spa, Tennis Courts, Wine Cellar",
    description: "Overlooking the Mediterranean Sea, Azure Coast Resort & Spa is a haven of French Riviera elegance. The resort features 150 suites, each with a private terrace and sea views, two Michelin-starred restaurants, and a world-class thalassotherapy center.",
    url: "https://example.com/azure-coast",
  },
  {
    hotel_name: "Brooklyn Bridge Boutique",
    slug: "brooklyn-bridge-boutique",
    address: "55 Water Street, DUMBO",
    country: "United States",
    city: "New York",
    category: "Boutique",
    stars: "4",
    rating: "4.5",
    number_of_reviews: "2104",
    price_per_night: "275",
    photo_url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
    languages_spoken: "English, Spanish",
    hotel_services: "Rooftop Bar, Co-Working Space, Pet Friendly, Bike Rental",
    amenities: "Gym, Sauna, Screening Room, Art Gallery",
    description: "A design-forward boutique hotel in Brooklyn's DUMBO neighborhood, steps from the iconic Brooklyn Bridge. Each of the 86 rooms features curated local artwork, custom-made furniture from Brooklyn artisans, and smart-home technology.",
    url: "https://example.com/brooklyn-bridge",
  },
  {
    hotel_name: "Riad Al-Noor",
    slug: "riad-al-noor",
    address: "Derb Dabachi 42, Medina",
    country: "Morocco",
    city: "Marrakech",
    category: "Heritage",
    stars: "4",
    rating: "4.9",
    number_of_reviews: "534",
    price_per_night: "180",
    photo_url: "https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=800",
    languages_spoken: "Arabic, French, English, Berber",
    hotel_services: "Traditional Hammam, Cooking Classes, Guided Tours, Airport Transfer",
    amenities: "Courtyard Pool, Rooftop Terrace, Library, Garden",
    description: "A meticulously restored 18th-century riad in the heart of the Medina. Riad Al-Noor features 12 individually designed suites with zellige tilework, carved cedar ceilings, and modern comforts. The central courtyard with its orange trees and fountain creates a peaceful oasis.",
    url: "https://example.com/riad-al-noor",
  },
  {
    hotel_name: "Nordic Fjord Lodge",
    slug: "nordic-fjord-lodge",
    address: "Geirangerveien 120",
    country: "Norway",
    city: "Geiranger",
    category: "Eco Lodge",
    stars: "4",
    rating: "4.7",
    number_of_reviews: "312",
    price_per_night: "345",
    photo_url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    languages_spoken: "Norwegian, English, German",
    hotel_services: "Northern Lights Tours, Fjord Cruises, Ski Shuttle, Sauna",
    amenities: "Hot Tub with Fjord View, Hiking Trails, Ski Storage, Fire Pit Lounge",
    description: "Perched above the UNESCO-listed Geirangerfjord, Nordic Fjord Lodge offers an immersive Scandinavian nature experience. The 24 timber cabins feature floor-to-ceiling glass walls, underfloor heating, and private hot tubs overlooking the fjord.",
    url: "https://example.com/nordic-fjord",
  },
  {
    hotel_name: "Marina Bay Residences",
    slug: "marina-bay-residences",
    address: "10 Bayfront Avenue",
    country: "Singapore",
    city: "Singapore",
    category: "Luxury",
    stars: "5",
    rating: "4.4",
    number_of_reviews: "1890",
    price_per_night: "450",
    photo_url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
    languages_spoken: "English, Mandarin, Malay, Tamil",
    hotel_services: "Infinity Pool, Casino, Shopping Mall, Convention Center",
    amenities: "Sky Park, Banyan Tree Spa, Celebrity Chef Restaurants, Art Science Museum Access",
    description: "An architectural marvel on Singapore's waterfront, Marina Bay Residences features 2,561 rooms across three 55-story towers. The iconic rooftop Sky Park spans all three towers and houses the world's largest rooftop infinity pool.",
    url: "https://example.com/marina-bay",
  },
  {
    hotel_name: "Hacienda del Sol",
    slug: "hacienda-del-sol",
    address: "Carretera Tulum-Boca Paila Km 7",
    country: "Mexico",
    city: "Tulum",
    category: "Resort",
    stars: "5",
    rating: "4.8",
    number_of_reviews: "678",
    price_per_night: "310",
    photo_url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
    languages_spoken: "Spanish, English, French",
    hotel_services: "Temazcal Ceremony, Yoga Classes, Cenote Tours, Beach Club",
    amenities: "Beachfront Pool, Jungle Spa, Farm-to-Table Restaurant, Cenote Access",
    description: "Located along Tulum's pristine Caribbean coastline, Hacienda del Sol harmonizes ancient Mayan heritage with contemporary eco-luxury. The 45 jungle villas feature private plunge pools, outdoor rain showers, and handwoven hammocks.",
    url: "https://example.com/hacienda-del-sol",
  },
  {
    hotel_name: "The Wool Shed Inn",
    slug: "wool-shed-inn",
    address: "12 Shotover Street, Queenstown",
    country: "New Zealand",
    city: "Queenstown",
    category: "Boutique",
    stars: "3",
    rating: "4.3",
    number_of_reviews: "421",
    price_per_night: "155",
    photo_url: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
    languages_spoken: "English, Maori",
    hotel_services: "Adventure Booking Desk, Ski Storage, Shuttle Service, BBQ Area",
    amenities: "Lake View Deck, Games Room, Drying Room, Guest Kitchen",
    description: "A charming boutique inn in the adventure capital of New Zealand. The Wool Shed combines rustic Kiwi character with comfortable modern amenities. Each of the 28 rooms is named after a local peak and features New Zealand wool furnishings.",
    url: "https://example.com/wool-shed",
  },
];

export const SAMPLE_DATA_SOURCE_NAME = "Sample Hotels Directory";

export const SAMPLE_LDP_TEMPLATE = {
  name: "Hotel Detail Page (LDP)",
  type: "listing_detail" as const,
  schemaType: "Hotel",
  urlPattern: "/hotel/{{slug}}",
};

export const SAMPLE_SRP_TEMPLATE = {
  name: "Hotels Search Results (SRP)",
  type: "search_results" as const,
  schemaType: "CollectionPage",
  urlPattern: "/hotels/{{slug}}",
};

export const SAMPLE_CATEGORY_SRP_TEMPLATE = {
  name: "Category Directory (SRP)",
  type: "category_page" as const,
  schemaType: "CollectionPage",
  urlPattern: "/category/{{slug}}",
};
